// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitStatus = { is_repo: boolean, branch: string | null, staged: Array<string>, modified: Array<string>, untracked: Array<string>, commits_ahead: number, commits_behind: number, };
