// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NewConfig {
    key: string;
    value: string;
    description: string | null;
}