// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProcessedTemplate {
    template_name: string;
    destination: string;
    content: string;
    output_path: string;
}