// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProcessStackRequest {
    stack_name: string;
    variables: Record<string, any>;
    target_directory: string | null;
}