// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { ProcessedTemplate } from './ProcessedTemplate';

export interface ProcessStackResult {
    stack_name: string;
    processed_templates: Array<ProcessedTemplate>;
    copied_files: Array<string>;
    errors: Array<string>;
}