// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tipo de archivo Quadlet soportado
 */
export type QuadletType = "container" | "network" | "volume" | "kube" | "pod" | "image" | "any";
