// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuadletStatus } from "./QuadletStatus";
import type { QuadletType } from "./QuadletType";

export type Quadlet = { 
/**
 * Nombre del archivo (sin extensión)
 */
name: string, 
/**
 * Tipo de Quadlet
 */
kind: QuadletType, 
/**
 * Descripción breve del Quadlet (opcional)
 */
description: string | null, 
/**
 * Contenido del archivo
 */
content: string | null, 
/**
 * Status actual del Quadlet
 */
status: QuadletStatus | null, };
