// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuadletStatus } from "./QuadletStatus";
import type { QuadletType } from "./QuadletType";

export type QuadletInfo = { 
/**
 * Nombre del quadlet (sin extensión)
 */
name: string, 
/**
 * Tipo de quadlet
 */
kind: QuadletType, 
/**
 * Status actual del quadlet
 */
status: QuadletStatus | null, };
