// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StackInfo { 
  name: string, 
  path: string, 
  files: Array<string>, 
  description: string | null, 
}