// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { TemplateStackInfo } from './TemplateStackInfo';

export interface TemplateStack {
    name: string;
    info: TemplateStackInfo;
    templates: Array<string>;
    static_files: Array<string>;
    outputs: Record<string, string>;
}